Repository Vezorla/vezorla-backend, pull requests merged in 2020-03, with the labels that each got.

#34 Login
  src/main/java/ca/sait/vezorla/controller/AuthenticationController.java
  src/main/java/ca/sait/vezorla/controller/AuthenticationRestController.java
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/controller/util/CustomerClientUtil.java
  src/main/java/ca/sait/vezorla/exception/AccountNotFoundException.java
  src/main/java/ca/sait/vezorla/exception/InvalidInputException.java
  src/main/java/ca/sait/vezorla/model/Account.java
  src/main/java/ca/sait/vezorla/model/AccountDiscount.java
  src/main/java/ca/sait/vezorla/model/Discount.java
  src/main/java/ca/sait/vezorla/model/Invoice.java
  src/main/java/ca/sait/vezorla/model/InvoiceReport.java
  src/main/java/ca/sait/vezorla/model/LineItem.java
  src/main/java/ca/sait/vezorla/model/Lot.java
  src/main/java/ca/sait/vezorla/model/Product.java
  src/main/java/ca/sait/vezorla/model/ProductQuantity.java
  src/main/java/ca/sait/vezorla/repository/AccountRepo.java
  src/main/java/ca/sait/vezorla/repository/DiscountRepo.java
  src/main/java/ca/sait/vezorla/service/AuthenticationServices.java
  src/main/java/ca/sait/vezorla/service/AuthenticationServicesImp.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: enhancement, test

#39 Create Account
  src/main/java/ca/sait/vezorla/controller/AuthenticationRestController.java
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/controller/util/CustomerClientUtil.java
  src/main/java/ca/sait/vezorla/exception/UnableToSaveException.java
  src/main/java/ca/sait/vezorla/model/Account.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: enhancement, test

#50 Finished update account
  src/main/java/ca/sait/vezorla/controller/AuthenticationRestController.java
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
  src/main/java/ca/sait/vezorla/controller/CustomerController.java
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/model/Account.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: client, enhancement, test

#54 Return 406 when password and repassword do not match
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/exception/PasswordMismatchException.java
Labels: customer, enhancement

#56 Applied Line items to invoice
  src/main/java/ca/sait/vezorla/controller/PaypalController.java
  src/main/java/ca/sait/vezorla/repository/InvoiceRepo.java
  src/main/java/ca/sait/vezorla/repository/LineItemRepo.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: customer, enhancement, review

#57 Finished Contact-Us email
  nano.save
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/controller/util/CustomerClientUtil.java
  src/main/java/ca/sait/vezorla/exception/UnableToSaveException.java
  src/main/java/ca/sait/vezorla/service/EmailServices.java
  src/main/java/ca/sait/vezorla/service/EmailServicesImp.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
  src/main/resources/application.properties
Labels: customer, enhancement, review, test

#62 Email Invoice to Customer after Checkout
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/controller/PaypalController.java
  src/main/java/ca/sait/vezorla/model/LineItem.java
  src/main/java/ca/sait/vezorla/service/EmailServices.java
  src/main/java/ca/sait/vezorla/service/EmailServicesImp.java
  src/main/java/ca/sait/vezorla/service/PaypalServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: client, customer, review

#70 Fixed 500 from check-role
  src/main/java/ca/sait/vezorla/controller/AuthenticationRestController.java
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: bug

#72 Jr view invoice client
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
  src/main/java/ca/sait/vezorla/model/Account.java
  src/main/java/ca/sait/vezorla/model/Invoice.java
  src/main/java/ca/sait/vezorla/model/LineItem.java
  src/main/java/ca/sait/vezorla/service/AccountServices.java
  src/main/java/ca/sait/vezorla/service/AccountServicesImp.java
Labels: client

#71 Add Product Refactor
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/model/Account.java
  src/main/java/ca/sait/vezorla/model/LineItem.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: enhancement

#75 View Order History on client's account - 100% complete
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
  src/main/java/ca/sait/vezorla/repository/InvoiceRepo.java
  src/main/java/ca/sait/vezorla/service/AccountServices.java
  src/main/java/ca/sait/vezorla/service/AccountServicesImp.java
Labels: client, enhancement

#78 Changed account pickup to boolean
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/model/Account.java
  src/main/java/ca/sait/vezorla/model/Invoice.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: bug

#79 Jr format price shop&out of stock json
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: review, test

#82 Client add to cart finished
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/controller/PaypalController.java
  src/main/java/ca/sait/vezorla/model/Cart.java
  src/main/java/ca/sait/vezorla/repository/CartRepo.java
  src/main/java/ca/sait/vezorla/repository/ProductRepo.java
  src/main/java/ca/sait/vezorla/service/AccountServices.java
  src/main/java/ca/sait/vezorla/service/AccountServicesImp.java
  src/main/java/ca/sait/vezorla/service/EmailServicesImp.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: client

#84 Return 401 if it is customer when checking role
  src/main/java/ca/sait/vezorla/controller/AuthenticationRestController.java
Labels: bug, customer

#86 Removed session setting after creating account
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
Labels: bug, customer

#88 Add Product Fixes
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/repository/CartRepo.java
  src/main/java/ca/sait/vezorla/service/AccountServices.java
  src/main/java/ca/sait/vezorla/service/AccountServicesImp.java
Labels: customer

#93 remove line item client
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/repository/LineItemRepo.java
  src/main/java/ca/sait/vezorla/service/AccountServices.java
  src/main/java/ca/sait/vezorla/service/AccountServicesImp.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: client, enhancement

#95 Update line item complete
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/service/AccountServices.java
  src/main/java/ca/sait/vezorla/service/AccountServicesImp.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: client, customer, enhancement

#89 UC29: Forgot password
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
  src/main/java/ca/sait/vezorla/controller/CustomerController.java
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/service/AuthenticationServices.java
  src/main/java/ca/sait/vezorla/service/AuthenticationServicesImp.java
  src/main/java/ca/sait/vezorla/service/EmailServices.java
  src/main/java/ca/sait/vezorla/service/EmailServicesImp.java
Labels: client, enhancement, review

#97 User Get Info
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/exception/OutOfStockException.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
  src/main/resources/application.properties
Labels: client, review, test

#100 Fixed email to send as JSON
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
  src/main/java/ca/sait/vezorla/service/AuthenticationServices.java
  src/main/java/ca/sait/vezorla/service/AuthenticationServicesImp.java
Labels: bug, enhancement

#102 Payment Transaction method after successful payment - 100% complete
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: review, test

#104 View all products for Admin login
  src/main/java/ca/sait/vezorla/controller/AdminRestController.java
  src/main/java/ca/sait/vezorla/service/AccountServicesImp.java
  src/main/java/ca/sait/vezorla/service/AdminServices.java
  src/main/java/ca/sait/vezorla/service/AdminServicesImp.java
Labels: admin

#107 Shipping info fix
  pom.xml
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/model/Account.java
  src/main/java/ca/sait/vezorla/model/Cart.java
  src/main/java/ca/sait/vezorla/model/LineItem.java
  src/main/java/ca/sait/vezorla/repository/LineItemRepo.java
  src/main/java/ca/sait/vezorla/service/AccountServices.java
  src/main/java/ca/sait/vezorla/service/AccountServicesImp.java
  src/main/java/ca/sait/vezorla/service/AdminServices.java
  src/main/java/ca/sait/vezorla/service/AdminServicesImp.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: bug

#115 Shipping temp account fix
  src/main/java/ca/sait/vezorla/controller/AuthenticationRestController.java
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/controller/PaypalController.java
  src/main/java/ca/sait/vezorla/exception/OutOfStockException.java
  src/main/java/ca/sait/vezorla/exception/UnauthorizedException.java
  src/main/java/ca/sait/vezorla/model/Account.java
  src/main/java/ca/sait/vezorla/repository/AccountDiscountRepo.java
  src/main/java/ca/sait/vezorla/service/AuthenticationServicesImp.java
  src/main/java/ca/sait/vezorla/service/PaypalServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
  src/main/java/ca/sait/vezorla/util/PaypalConfig.java
Labels: bug

#117 Refactored most shop methods
  src/main/java/ca/sait/vezorla/controller/AuthenticationRestController.java
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/controller/PayPalController.java
  src/main/java/ca/sait/vezorla/service/AccountServices.java
  src/main/java/ca/sait/vezorla/service/AccountServicesImp.java
  src/main/java/ca/sait/vezorla/service/AdminServicesImp.java
  src/main/java/ca/sait/vezorla/service/AuthenticationServicesImp.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: review, test

#120 Small refactor for view order history
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
  src/main/java/ca/sait/vezorla/service/AccountServices.java
  src/main/java/ca/sait/vezorla/service/AccountServicesImp.java
Labels: refactor

#124 Subscription is set to false during shipping info fix
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
  src/main/java/ca/sait/vezorla/controller/CustomerRestController.java
  src/main/java/ca/sait/vezorla/model/Account.java
  src/main/java/ca/sait/vezorla/service/AccountServicesImp.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: bug

#125 Send email when creating account
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
  src/main/java/ca/sait/vezorla/model/Account.java
  src/main/java/ca/sait/vezorla/service/AccountServicesImp.java
  src/main/java/ca/sait/vezorla/service/EmailServices.java
  src/main/java/ca/sait/vezorla/service/EmailServicesImp.java
Labels: enhancement

#131 Fixed create account email bug
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
Labels: bug, client

#133 Create PO and create product tested and good
  src/main/java/ca/sait/vezorla/controller/AdminRestController.java
  src/main/java/ca/sait/vezorla/exception/PasswordMismatchException.java
  src/main/java/ca/sait/vezorla/exception/ProductAlreadyExistsException.java
  src/main/java/ca/sait/vezorla/model/AccountDiscount.java
  src/main/java/ca/sait/vezorla/model/Backup.java
  src/main/java/ca/sait/vezorla/model/Lot.java
  src/main/java/ca/sait/vezorla/model/Product.java
  src/main/java/ca/sait/vezorla/model/PurchaseOrder.java
  src/main/java/ca/sait/vezorla/repository/ProductRepo.java
  src/main/java/ca/sait/vezorla/service/AccountServices.java
  src/main/java/ca/sait/vezorla/service/AdminServices.java
  src/main/java/ca/sait/vezorla/service/AdminServicesImp.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: admin, enhancement

#135 Added verification for product creation
  src/main/java/ca/sait/vezorla/controller/AdminRestController.java
  src/main/java/ca/sait/vezorla/model/Product.java
  src/main/java/ca/sait/vezorla/service/AdminServices.java
  src/main/java/ca/sait/vezorla/service/AdminServicesImp.java
Labels: admin, bug, enhancement

#141 View Order History for admin 100% complete for backend
  src/main/java/ca/sait/vezorla/controller/AdminRestController.java
  src/main/java/ca/sait/vezorla/controller/ClientRestController.java
  src/main/java/ca/sait/vezorla/model/Discount.java
  src/main/java/ca/sait/vezorla/repository/InvoiceRepo.java
  src/main/java/ca/sait/vezorla/service/AdminServices.java
  src/main/java/ca/sait/vezorla/service/AdminServicesImp.java
Labels: admin, test

#142 Update Product Finished
  src/main/java/ca/sait/vezorla/controller/AdminRestController.java
  src/main/java/ca/sait/vezorla/model/Product.java
  src/main/java/ca/sait/vezorla/repository/ProductRepo.java
  src/main/java/ca/sait/vezorla/service/AdminServices.java
  src/main/java/ca/sait/vezorla/service/AdminServicesImp.java
  src/main/java/ca/sait/vezorla/service/UserServices.java
  src/main/java/ca/sait/vezorla/service/UserServicesImp.java
Labels: admin, enhancement

#145 Jr export and restore
  pom.xml
  src/main/java/ca/sait/vezorla/controller/AdminRestController.java
  src/main/java/ca/sait/vezorla/service/AdminServices.java
  src/main/java/ca/sait/vezorla/service/AdminServicesImp.java
Labels: admin
